"use client";
// Feature matrix: composable overlay-driven 2-tab layout.
// Matrix tab: overlay toggles control which visual layers render.
// Ops tab: probe status grid (unchanged from legacy).
import { useCallback, useMemo } from "react";
import { FeatureGrid } from "@/components/feature-grid";
import type { CellContext } from "@/components/feature-grid";
import { StatusTab } from "@/components/status-tab";
import { useLiveStatus } from "@/hooks/useLiveStatus";
import { useProbes, useTriggerProbe } from "@/hooks/use-probes";
import { mergeRowsToMap } from "@/lib/live-status";
import { useOverlays } from "@/hooks/useOverlays";
import { OverlayToggleBar } from "@/components/overlay-toggle-bar";
import { ComposedCell } from "@/components/composed-cell";
import { AdaptiveStatsBar } from "@/components/adaptive-stats-bar";
import { AdaptiveLegend } from "@/components/adaptive-legend";
import type { ParityTier } from "@/components/parity-badge";
import { getDocsStatus } from "@/lib/docs-status";
import type { CatalogCell } from "@/components/depth-utils";
import catalog from "@/data/catalog.json";
import type { CatalogData } from "@/data/catalog-types";

// Single cast: catalog.json is generated by `pretest`/`predev`/`prebuild` from
// generate-registry.ts and conforms to CatalogData by construction.
const catalogData: CatalogData = catalog as CatalogData;

export default function Page() {
  // Single subscription for ALL dimensions — no filter. Avoids the 7-way
  // SSE race that caused PB subscribe 400s when 7 hooks competed for the
  // single PB SDK realtime connection during hydration.
  const allStatus = useLiveStatus();

  const liveStatus = useMemo(
    () => mergeRowsToMap(allStatus.rows),
    [allStatus.rows],
  );

  const connection = allStatus.status;

  // R2-D.1: real probe wiring. `useProbes` polls the ops API every 10s and
  // feeds the schedule grid; `useTriggerProbe` POSTs to /trigger with the
  // operator token. If the token is unset, the trigger callback throws
  // a clear "token required" error from useTriggerProbe — fail-loud so
  // operators see the issue rather than a silent no-op.
  const probesQuery = useProbes();
  const probeEntries = useMemo(
    () => probesQuery.data?.probes ?? [],
    [probesQuery.data],
  );
  const triggerToken = process.env.NEXT_PUBLIC_OPS_TRIGGER_TOKEN;
  const { trigger } = useTriggerProbe({ token: triggerToken });
  const handleTrigger = useCallback(
    async (probeId: string, slugs?: string[]): Promise<void> => {
      await trigger(probeId, slugs);
    },
    [trigger],
  );

  // Overlay state management (handles URL hash + localStorage persistence)
  const { overlays, activeTab, toggle, applyPreset, setTab, activePreset } =
    useOverlays();

  // Build a cell-lookup map: integration slug + feature id -> CatalogCell
  const cellLookup = useMemo(() => {
    const map = new Map<string, CatalogCell>();
    for (const cell of catalogData.cells) {
      if (cell.feature !== null) {
        map.set(`${cell.integration}:${cell.feature}`, cell);
      }
    }
    return map;
  }, []);

  // Compute health stats from column tallies (aggregate across integrations)
  // Reuse the computeColumnTally logic from feature-grid.
  // For the stats bar, we aggregate from catalog cell data.
  const healthStats = useMemo(() => {
    let green = 0;
    let amber = 0;
    let red = 0;
    for (const cell of catalogData.cells) {
      if (cell.status === "wired") green++;
      else if (cell.status === "stub") amber++;
      // unshipped doesn't count as red for health
    }
    return { green, amber, red };
  }, []);

  // Compute parity tier counts
  const parityStats = useMemo(() => {
    const counts: Record<ParityTier, number> = {
      reference: 0,
      at_parity: 0,
      partial: 0,
      minimal: 0,
      not_wired: 0,
    };
    // Count unique integrations by tier
    const seen = new Set<string>();
    for (const cell of catalogData.cells) {
      if (!seen.has(cell.integration)) {
        seen.add(cell.integration);
        counts[cell.parity_tier as ParityTier]++;
      }
    }
    return counts;
  }, []);

  // Compute docs reachability stats from unique feature IDs
  const docsStats = useMemo(() => {
    let ok = 0;
    let missing = 0;
    let notFound = 0;
    let error = 0;
    const seen = new Set<string>();
    for (const cell of catalogData.cells) {
      if (cell.feature !== null && !seen.has(cell.feature)) {
        seen.add(cell.feature);
        const status = getDocsStatus(cell.feature);
        if (status.og === "ok") ok++;
        else if (status.og === "missing") missing++;
        else if (status.og === "notfound") notFound++;
        else if (status.og === "error") error++;
      }
    }
    return { ok, missing, notFound, error };
  }, []);

  // renderCell callback wrapping ComposedCell
  const renderCell = useCallback(
    (ctx: CellContext) => {
      const catalogCell = cellLookup.get(
        `${ctx.integration.slug}:${ctx.feature.id}`,
      );
      return (
        <ComposedCell ctx={ctx} overlays={overlays} catalogCell={catalogCell} />
      );
    },
    [overlays, cellLookup],
  );

  return (
    <div data-testid="tab-shell">
      {/* 2-tab bar: Matrix | Ops */}
      <div className="flex items-center gap-0 border-b border-[var(--border)] px-8">
        <button
          type="button"
          data-testid="tab-matrix"
          onClick={() => setTab("matrix")}
          className={`px-4 py-2.5 text-sm font-medium transition-colors cursor-pointer ${
            activeTab === "matrix"
              ? "text-[var(--accent)] border-b-2 border-[var(--accent)] -mb-px"
              : "text-[var(--text-muted)] hover:text-[var(--text-secondary)]"
          }`}
        >
          Matrix
        </button>
        <button
          type="button"
          data-testid="tab-ops"
          onClick={() => setTab("ops")}
          className={`px-4 py-2.5 text-sm font-medium transition-colors cursor-pointer ${
            activeTab === "ops"
              ? "text-[var(--accent)] border-b-2 border-[var(--accent)] -mb-px"
              : "text-[var(--text-muted)] hover:text-[var(--text-secondary)]"
          }`}
        >
          Ops
        </button>
      </div>

      {/* Tab content */}
      {activeTab === "matrix" && (
        <>
          <div className="sticky top-0 z-30 px-8 py-3 flex flex-col gap-3 bg-[var(--bg-surface)] border-b border-[var(--border)]">
            <OverlayToggleBar
              overlays={overlays}
              onToggle={toggle}
              onApplyPreset={applyPreset}
              activePreset={activePreset}
            />
            <AdaptiveStatsBar
              overlays={overlays}
              catalog={catalogData}
              healthStats={healthStats}
              parityStats={parityStats}
              docsStats={docsStats}
            />
          </div>
          <FeatureGrid
            title="Feature Matrix"
            renderCell={renderCell}
            minColWidth={260}
            liveStatus={liveStatus}
            connection={connection}
            overlays={overlays}
            catalog={catalogData}
          />
          <AdaptiveLegend overlays={overlays} />
        </>
      )}

      {activeTab === "ops" && (
        <StatusTab entries={probeEntries} onTrigger={handleTrigger} />
      )}
    </div>
  );
}
